# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TESTIBMSPEECH' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	pod 'Firebase/Core'
	pod 'Firebase/Core'
    	pod 'Firebase/Messaging'
    	pod 'Firebase/Database'
    	pod 'Firebase/Crash'
	pod 'Firebase/Storage'

end
